<?php

namespace App\Http\Controllers;

use App\Models\Mapel;
use Illuminate\Http\Request;

class mapelController extends Controller
{
    public function datamapel()
    {
        try {
            $mapels = Mapel::all();

            return view('manajemen-mapel.mapel', compact('mapels'));
        } catch (\Exception $e) {
            return back()->with('gagal', 'Data Gagal DimuatğŸ˜µ');
        }
    }

    public function tambahmapel()
    {
        return view('manajemen-mapel.tambah-mapel', ['hideNavbar' => true]);
    }

    public function storesubject(Request $request)
    {
        $validated = $request->validate([
            'nama_mapel' => 'required|string|max:50'
        ]);

        try {
            Mapel::create([
                'nama_mapel' => $validated['nama_mapel']
            ]);

            return redirect('/subject')->with('sukses', "Data Berhasil DitambahkanğŸ¥³");
        } catch (\Exception $e) {
            return redirect("/addsubject")->with('gagal', "Data Gagal DitambahkanğŸ˜µ");
        }
    }

    public function editmapel($id)
    {
        $mapel = Mapel::find($id);

        if (!$mapel) {
            return back()->with('gagal', 'Mapel Tidak DitemukanğŸ˜µ');
        }

        return view('manajemen-mapel.edit-mapel', ['hideNavbar' => true], compact('mapel'));
    }

    public function updatesubject(Request $request, $id)
    {
        $validated = $request->validate([
            'nama_mapel' => 'required|string|max:50'
        ]);

        $mapel = Mapel::findOrFail($id);

        try {
            $mapel->update([
                'nama_mapel' => $validated['nama_mapel']
            ]);

            return redirect('/subject')->with('sukses', "Data Berhasil DieditğŸ¥³");
        } catch (\Exception $e) {
            return redirect("/editsubject/$mapel->id")->with('gagal', "Data Gagal DieditğŸ˜µ");
        }
    }

    public function hapusmapel($id)
    {
        try {
            Mapel::findOrFail($id);
            Mapel::destroy($id);

            return redirect()->back()->with('sukses', "Data Berhasil DihapusğŸ¥³");
        } catch (\Exception $e) {
            return redirect()->back()->with('gagal', "Data Gagal DihapusğŸ˜µ");
        }
    }
}
